[theme]
base = "dark"
primaryColor = "#4f9169"
backgroundColor = "#10150f"
secondaryBackgroundColor = "#182015"
textColor = "#f2f4ef"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8502

[browser]
gatherUsageStats = false
